# Site setings
name: "CloudSafari"
description: "Life is a journey. And the cloud is inheriting our life's complexity. From time to time, I'll have a safari trip into the cloud and this is my journal of what I learned. Not sure if it's useful to you but I hope it will be"
meta_description: "Cloud,Microsoft,Azure,Synapse Analytics,Databricks,Data Factory,Data Lake, Azure Functions"
logo: 
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://cloudsafari.ca/
disqus: 'justgoodthemes'
mailchimp_url: '//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
cover_image: bc_1.jpg
# Add your GA Tracking Id
ga_analytics: 


# Author
author:
  name: 'Mohamed Sharaf'
  image: 'authorimage.jpg'
  greetings: 'Hey all!'
  description: "I'm me"
  bio: 'To be added'

# Contact form setings
email: 
contact_page_description: 
thankyou_page_description: 

# Social links
twitter: '@mohamsharaf'
facebook: 
github: 'mosharafMS'
codepen: 
dribbble: 
medium: '@mohamed.sharaf'
instagram: 
pinterest: 
linkedin: 'mosharafms'
producthunt: 

# Navigation
navigation:
  - text: About
    url: /about/


# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
