# Site setings
name: "CloudSafari"
description: "Life is a journey. And the cloud is inheriting our life's complexity. From time to time, I'll have a safari trip into the cloud and this is my journal of what I learned. Not sure if it's useful to you but I hope it will be"
meta_description: "Cloud,Microsoft,Azure,Synapse Analytics,Databricks,Data Factory,Data Lake, Azure Functions"
logo: 
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://cloudsafari.ca/
disqus: 
mailchimp_url: 
cover_image: bc_1.jpg
# Add your GA Tracking Id
ga_analytics: "UA-177612139-1"



# Author
author:
  name: 'Mohamed Sharaf'
  image: 'authorimage.jpg'
  greetings: 'Hey all!'
  description: "Life is a journey. And the cloud is inheriting our life's complexity. From time to time, I'll have a safari trip into the cloud and this is my journal of what I learned. Not sure if it is useful to you but I hope it will be"
  bio: 'Thank you for visiting my blog. I am Mohamed Sharaf and here is what I would describe myself: Curious to learn. Still excited of life despite all the misery in it. Love intelligent debate and knowing intelligent people. Current professional role is Cloud Solution Architect. Amateur cyclist though I do not think I will write about my hobby here. This blog is my personal way to provide high quality material to help a fellow learner understand something, anything. I will not write until there is something worth writing and I will try to update it and engage with comments regularly.'

# Contact form setings
email: 
contact_page_description: 
thankyou_page_description: 

# Social links
twitter: '@mohamsharaf'
facebook: 
github: 'mosharafMS'
codepen: 
dribbble: 
medium: '@mohamed.sharaf'
instagram: 
pinterest: 
linkedin: 'mosharafms'
producthunt: 

# Navigation
navigation:
  - text: About
    url: /about/


# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:year/:month/:categories/:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
