# Site setings
name: "CloudSafari"
description: "CloudSafari is my personal window to share about my work and technical projects. All information are provided as is and my views only represent myself"
meta_description: "Cloud,Microsoft,Azure,Synapse Analytics,Databricks,Data Factory,Data Lake, Azure Functions"
logo: 
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://cloudsafari.ca/
disqus: 'cloudsafari-ca'
mailchimp_url: 
cover_image: bc_1.jpg
# Add your GA Tracking Id
ga_analytics: "UA-177612139-1"



# Author
author:
  name: 'Mohamed Sharaf'
  image: 'authorimage.jpg'
  greetings: ''
  description: ""
  bio: 'Mohamed Sharaf, Cloud Solution Architect at Microsoft and curious to learn something new. Love intelligent debate and knowing intelligent people. Amateur cyclist though I do not think I will write about my hobby here. This blog is my personal way to provide high quality material to help a fellow learner understand something, anything. I will not write until there is something worth writing and I will try to update it and engage with comments regularly.'

# Contact form setings
email: 
contact_page_description: 
thankyou_page_description: 

# Social links
twitter: '@mohamsharaf'
facebook: 
github: 'mosharafMS'
codepen: 
dribbble: 
medium: '@mohamed.sharaf'
instagram: 
pinterest: 
linkedin: 'mosharafms'
producthunt: 

# Navigation
navigation:
  - text: About
    url: /about/


# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-spaceship

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:year/:month/:categories/:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed


#spaceship plugin
jekyll-spaceship:
  media-processor:
    default:
      id: 'media-{id}'
      class: 'media'
      width: '100%'
      height: 50
      frameborder: 0
      style: 'max-width: 600px; outline: none;'
      allow: 'encrypted-media; picture-in-picture'